### ISSUE TITLE
DWA

### ISSUE THREAD

**Issue by pvela2017** [mefisto2017/KSAM-2022-Robotic-Competition#1]
**Description**

Add DWA to our ROS package.

**Tasks**
- [x]  Test TEB in real world
- [x]  Tune TEB in real world
- [ ]  Create more scenarios in Gazebo

- [x] #8
- [x]  Tune TEB
- [x]  Test  TEB in Gazebo
- [x]  Add DWA
- [x]  Test it on Gazebo
- [x]  Test it with real robot
