### ISSUE TITLE
Fix Gazebo model according to our real robot

### ISSUE THREAD

**Issue by pvela2017** [mefisto2017/KSAM-2022-Robotic-Competition#2]
**Description**
Adapt our simulation model to our actual robot

**Tasks**
- [x]  Change Lidar range
- [ ]  Set Lidar position as the one we will use in the real robot
- [ ]  Set cameras position as the one we will use in the real robot
- [ ]  Set cameras parameters ( FOV, etc)
- [ ]  Modify robot structure (optional)
- [ ]  Test in Gazebo
