### ISSUE TITLE
Real robot

### ISSUE THREAD

**Issue by pvela2017** [mefisto2017/KSAM-2022-Robotic-Competition#7]
**Description**

Tasks to complete our real robot. (2 robots)

**Tasks**

- [x]  Install ubuntu 20.04
- [x]  Install ros-noetic
- [x]  Install graphical env.
- [x]  Install VNC
- [x]  Setup VNC
- [x]  Check all the ros package are installed by running our repo.
- [x]  Design piece to mount cameras.
- [x]  Test IMU.
- [x]  Test LIDAR
- [x]  Make real obstacles
- [x]  Decrease height of the robot
- [x]  Design piece to mount Jetson Nano on the back
- [x]  Mount Jetson Nano
- [x]  Implement LEDs.
- [x]  Implement launch button for the competition.
- [x]  Fix Lidar position and give me the x,y,z coordinates.
- [x]  Define our test cases for the real robot.
**Doheon**
- [x]  Mount cameras.
- [x]  Test cameras.
- [x] Print 2 board bridge
- [x] Back on NX2
- [x] Connect 2 board
- [x] Connect fan
- [x] 아크릴
- [x] Standing tree without bottom tree
